// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACsBuxa7yJDPOyYVcZsSXw8C2egBhV9tA',
    appId: '1:10231355415:web:81cb2a8e7156c50eb2e452',
    messagingSenderId: '10231355415',
    projectId: 'propertylistingapp-da67c',
    authDomain: 'propertylistingapp-da67c.firebaseapp.com',
    storageBucket: 'propertylistingapp-da67c.firebasestorage.app',
    measurementId: 'G-1XKJ67RZ83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCE7cgsCz8oLHaub8wJrIq_r7vVvKLuw',
    appId: '1:10231355415:android:a144837db77c9535b2e452',
    messagingSenderId: '10231355415',
    projectId: 'propertylistingapp-da67c',
    storageBucket: 'propertylistingapp-da67c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeH7ResIwh6qPfbNDC5H5HUptQLswrHY4',
    appId: '1:10231355415:ios:dac6bf9d0484e8e7b2e452',
    messagingSenderId: '10231355415',
    projectId: 'propertylistingapp-da67c',
    storageBucket: 'propertylistingapp-da67c.firebasestorage.app',
    iosBundleId: 'com.example.propertyListingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeH7ResIwh6qPfbNDC5H5HUptQLswrHY4',
    appId: '1:10231355415:ios:dac6bf9d0484e8e7b2e452',
    messagingSenderId: '10231355415',
    projectId: 'propertylistingapp-da67c',
    storageBucket: 'propertylistingapp-da67c.firebasestorage.app',
    iosBundleId: 'com.example.propertyListingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACsBuxa7yJDPOyYVcZsSXw8C2egBhV9tA',
    appId: '1:10231355415:web:d6be0fc3a3c7f862b2e452',
    messagingSenderId: '10231355415',
    projectId: 'propertylistingapp-da67c',
    authDomain: 'propertylistingapp-da67c.firebaseapp.com',
    storageBucket: 'propertylistingapp-da67c.firebasestorage.app',
    measurementId: 'G-EE0PCPL5BD',
  );
}
